#! /usr/bin/env bash

(
CSEARCH_WROKSPACE="$MY_DOTFILES_RESOURCES/code_reading_utils/code";

if [[ ! -d "$CSEARCH_WROKSPACE" ]];then
    mkdir -p "$CSEARCH_WROKSPACE"
fi

CURRENT_DIR="${PWD//\//_}";
export CSEARCHINDEX="$CSEARCH_WROKSPACE/$CURRENT_DIR.csearchindex";
cindex $PWD;

if [[ -f "$HOME/.csearchindex" ]];then
    rm -v "$HOME/.csearchindex"
fi
)
