#! /usr/bin/env bash

(
CSEARCH_WROKSPACE="$MY_DOTFILES_RESOURCES/code_reading_utils/code";
CURRENT_DIR="${PWD//\//_}";
export CSEARCHINDEX="$CSEARCH_WROKSPACE/$CURRENT_DIR.csearchindex";

if [[ -f "$CSEARCHINDEX" ]];then
    pattern='('
    pattern+='no such file or directory'
    pattern+=')'
    csearch -n "$@" |& s -i -v "$pattern"
else
    echo "plz do _cindex first"
fi
)
