#! /usr/bin/env bash

(
FSEARCH_WORKSPACE="$MY_DOTFILES_RESOURCES/code_reading_utils/file";

if [[ ! -d "$FSEARCH_WORKSPACE" ]];then
    mkdir -p "$FSEARCH_WORKSPACE"
fi

CURRENT_DIR="${PWD//\//_}";
export FSEARCHINDEX="$FSEARCH_WORKSPACE/$CURRENT_DIR.file.index";

# find . -not -path '*/\.*' -type f | _readlink | sort | uniq > $FSEARCHINDEX
# here we do not use pythonfind because of its poor performance
find . -not -path '*/\.*' -type f | _readlink > $FSEARCHINDEX
)
