#! /usr/bin/env bash

(
SEARCH_WORKSPACE="$MY_DOTFILES_RESOURCES/code_reading_utils/file";

if [[ ! -d "$SEARCH_WORKSPACE" ]];then
    mkdir -p "$SEARCH_WORKSPACE"
fi

CURRENT_DIR="${PWD//\//_}";
export SEARCHINDEX="$SEARCH_WORKSPACE/$CURRENT_DIR.file.index";

if [[ ! -f "$SEARCHINDEX" ]];then
    echo "plz do _findex first"
else
    if [[ "$#" -eq 0 ]];then
        cat "$SEARCHINDEX"
    else
        s -f "$SEARCHINDEX" "$@"
    fi
fi
)
