#! /usr/bin/env bash

(
FSEARCH_WORKSPACE="$HOME/.code_reading_utils/file";

if [[ ! -d "$FSEARCH_WORKSPACE" ]];then
    mkdir -p "$FSEARCH_WORKSPACE"
fi

CURRENT_DIR="${PWD//\//_}";
export FSEARCHINDEX="$FSEARCH_WORKSPACE/$CURRENT_DIR.index";

if [[ ! -f "$FSEARCHINDEX" ]];then
    echo "$FSEARCHINDEX not exist"
fi

s -f "$FSEARCHINDEX" "$@"
)
