#! /usr/bin/env bash

(
FSEARCH_WORKSPACE="$MY_DOTFILES_RESOURCES/code_reading_utils/file";

if [[ ! -d "$FSEARCH_WORKSPACE" ]];then
    mkdir -p "$FSEARCH_WORKSPACE"
fi

CURRENT_DIR="${PWD//\//_}";
export FSEARCHINDEX="$FSEARCH_WORKSPACE/$CURRENT_DIR.index";

if [[ ! -f "$FSEARCHINDEX" ]];then
    echo "plz do _findex first"
else
    s -f "$FSEARCHINDEX" "$@"
fi
)
