#! /usr/bin/env bash

if [[ "$#" -lt 2 ]];then
    echo "Usage: $0 <extension> <pattern>"
else
    extension="$1"
    shift 1
    rg --no-heading --ignore-file "$MY_SH_MODULE/code_reading/resource/ripgrep.ignore" --type-add "foo:*.$extension" -tfoo $@
fi
