#! /usr/bin/env bash

echo "generating file list for current directory ..."
find . -type f -iname '*.aidl' -o -iname '*.cc' -o -iname '*.h' -o -iname '*.c' -o -iname '*.cpp' -o -iname '*.java' | s -i -v 'test' | _readlink | sort | uniq > './cscope.files'
echo "output: cscope.files"

