#! /usr/bin/env bash

# currently, cscope just had poor performance while handling large code-base, so just disable it

if [[ ! -f './cscope.files' ]];then
    echo "generating file list for current directory ..."

    white_list='('
    white_list+='\.aidl'
    white_list+='|\.cc'
    white_list+='|\.h'
    white_list+='|\.c'
    white_list+='|\.cpp'
    white_list+='|\.java'
    white_list+='|\.hpp'
    white_list+=')'

    black_list='('
    black_list+='test'
    black_list+=')'


    find . -type f | pythongrep -i "$white_list" | pythongrep -i -v "$black_list" | _readlink | sort | uniq > './cscope.files'
    echo "output: cscope.files"
fi

_is_command_exist() {
    [[ "$#" -eq 1 ]] && command -v "$1" > /dev/null
}

#if ! _is_command_exist 'cscope';then
#   echo "install cscope first" 
#   exit
#fi

if ! _is_command_exist 'ctags';then
   echo "install ctags first" 
   exit
fi

if ! _is_command_exist 'gtags';then
   echo "install gtags first" 
   exit
fi

# the indexing process

if [[ -f './cscope.files' ]];then
    #echo "cscope indexing ..."
    #cscope -bcekq -i './cscope.files'

    echo "ctags indexing ..."
    ctags -L ./cscope.files --tag-relative=yes './tags'

    echo "gnu-global indexing ..."
    # gtags on ubuntu does not support '--skip-unreadable'
    gtags -f ./cscope.files
else
    echo "Plz generate file list first!"
fi
