#! /usr/bin/env bash

# csfa - csearch for aosp


pattern='('

pattern+='aosp/cts'
pattern+='|aosp/developers'
pattern+='|aosp/development'
pattern+='|aosp/device'
pattern+='|aosp/hardware'
pattern+='|aosp/prebuilts'
pattern+='|aosp/tools/'

pattern+='|examples'
pattern+='|packages'
pattern+='|sdk'
pattern+='|test'

pattern+='|.html'
pattern+='|.js'
pattern+='|.xml'
pattern+='|.txt'
pattern+='|.py'

pattern+='|no such file or directory'

pattern+=')'

_csearch "$@" |& s -i -v "$pattern"

unset pattern
