#! /usr/bin/env bash

# dsa - dsearch for aosp

if [[ "$#" -lt 1 ]];then
    exit
fi

pattern='('

pattern+='examples'
pattern+='|packages'
pattern+='|test'
pattern+='|\.git\\'
pattern+='|\.html'
pattern+='|\.py'
pattern+='|\.repo\\'
pattern+='|\.txt'
pattern+='|\.xml'

pattern+=')'

_fsearch "$@" | pythongrep -i -v "$pattern"

unset pattern
