#! /usr/bin/env bash

# dsa - dsearch for aosp

pattern='('

pattern+='examples'
pattern+='|packages'
pattern+='|test'
pattern+='|\.git\\'
pattern+='|\.html'
pattern+='|\.py'
pattern+='|\.repo\\'
pattern+='|\.txt'
pattern+='|\.xml'

pattern+=')'

_fsearch "$@" | s -i -v "$pattern"

unset pattern
