#! /usr/bin/env bash

# csfa - csearch for aosp

pattern='('

pattern+='examples'
pattern+='|packages'
pattern+='|test'

pattern+='|\.html'
pattern+='|\.py'
pattern+='|\.txt'
pattern+='|\.xml'

pattern+=')'

_fsearch "$@" | s -i -v "$pattern"

unset pattern
