#! /usr/bin/env bash

# fsa - fsearch for aosp

if [[ "$#" -lt 1 ]];then
    exit
fi

pattern='('

pattern+='examples'
pattern+='|test'

pattern+='|\.git\\'
pattern+='|\.html'
pattern+='|\.py'
pattern+='|\.repo\\'
pattern+='|\.txt'
pattern+='|\.xml'

pattern+=')'

_fsearch "$@" | s -i -v "$pattern"

unset pattern
