#! /usr/bin/env bash

_is_darwin() {
    [[ "$#" -eq 0 ]] && [[ "$(uname -s)" == "Darwin" ]]
}

_is_linux() {
    [[ "$#" -eq 0 ]] && [[ "$(uname -s)" == "Linux" ]]
}

VERSION_CODE="$(location https://github.com/BurntSushi/ripgrep/releases/latest | s -o "(?<=tag/).*(?=$)")"

if _is_darwin;then
    OUTPUT_FILE_NAME="ripgrep-$VERSION_CODE-x86_64-apple-darwin.tar.gz"
elif _is_linux;then
    OUTPUT_FILE_NAME="ripgrep-$VERSION_CODE-i686-unknown-linux-musl.tar.gz"
fi

curl -k -L -C - "https://github.com/BurntSushi/ripgrep/releases/download/$VERSION_CODE/$OUTPUT_FILE_NAME" -o "$HOME/bin/$OUTPUT_FILE_NAME" && tar xf "$HOME/bin/$OUTPUT_FILE_NAME" -C ~/bin
