#! /usr/bin/env bash

OUTPUT_FILE_NAME="ripgrep-temp.tar.gz"

INPUT_URL="$(github_get_latest_asset BurntSushi/ripgrep | percol)"

if [[ ! -z "$INPUT_URL" ]];then
    # https://www.davidpashley.com/articles/writing-robust-shell-scripts/
    trap "rm -vf $HOME/bin/$OUTPUT_FILE_NAME; exit" INT TERM EXIT
    curl -k -L -C - "$INPUT_URL" -o "$HOME/bin/$OUTPUT_FILE_NAME" && tar xf "$HOME/bin/$OUTPUT_FILE_NAME" -C ~/bin
    rm -vf "$HOME/bin/$OUTPUT_FILE_NAME"
    trap - INT TERM EXIT
else
    echo "need pick a valid url"
fi
