#! /usr/bin/env bash

if [[ "$(uname -s)" == 'Darwin' ]];then
    if [[ -f "/opt/local/bin/port" ]];then
        echo "check https://github.com/Valloric/YouCompleteMe/issues/8"
        if [[ "$(port select --list python | s active | s -o '(?<=^).*?(?=\()')" == 'none' ]];then
            echo "With Macports, please do 'sudo port select --set python python27'";
            exit
        fi

        #if [[ "$(port select --list gcc | s active | s -o '(?<=^).*?(?=\()')" == 'none' ]];then
        #    echo "With Macports, I use the gcc49 as CMAKE_C_COMPILER & CMAKE_CXX_COMPILER"
        #    exit
        #fi

        if [[ ! -f "/opt/local/bin/cmake" ]];then
            echo "With Macports, I use the cmake as the CMAKE_MAKE_PROGRAM"
        fi

        # https://github.com/Valloric/YouCompleteMe/issues/679
        (cd "$HOME/.vim/bundle/YouCompleteMe";

        export CMAKE_MAKE_PROGRAM='/opt/local/bin/cmake'

        # in order to \'enable --clang-completer\', I use the `port install llvm-3.9`, and then un-comment below too line
        export PATH_TO_LLVM_ROOT='/opt/local/libexec/llvm-3.9'
        export EXTRA_CMAKE_ARGS="-DPYTHON_EXECUTABLE=/opt/local/bin/python, -DPATH_TO_LLVM_ROOT=$PATH_TO_LLVM_ROOT"

        # third_party/ycmd/cpp/ycm/CMakeLists.txt
        # add_custom_command( TARGET ${PROJECT_NAME}
        #                      POST_BUILD
        #                      COMMAND install_name_tool
        #                      "-delete_rpath"
        #                      "@executable_path/../lib"
        #                      "$<TARGET_FILE_DIR:${PROJECT_NAME}>/${LIBCLANG_TAIL}"
        #                    )
        # this `@executable_path/../lib` assumes the `libclang.dylib` is located in the path $(which install_name_tool)/../lib
        # sadly for macports, it\'s /opt/local/bin/install_name_tool and /opt/local/libexec/llvm-3.9/lib/libclang.dylib
        # so in order to compile, we must change `@executable_path/../lib` to `/opt/local/libexec/llvm-3.9/lib` 

        export CMAKE_C_COMPILER="/opt/local/bin/clang"
        export CMAKE_CXX_COMPILER="/opt/local/bin/clang"

        unset PATH;
        export PATH="/bin"
        export PATH="/opt/local/sbin:$PATH";
        export PATH="/opt/local/bin:$PATH";
        export PATH="/opt/local/libexec/gnubin:$PATH";
        echo $PATH
        echo $PATH_TO_LLVM_ROOT
        #python ./install.py)
        python ./install.py --clang-completer)
    else
        (cd "$HOME/.vim/bundle/YouCompleteMe";
        unset PATH;
        export PATH="/bin"
        export PATH="/usr/bin/:$PATH"
        export PATH="/usr/local/bin:$PATH";
        echo $PATH
        #python ./install.py)
        python ./install.py --clang-completer)
    fi
fi
