_annotation_completion_write git clone
_annotation_completion_write git init
_annotation_completion_write git add
_annotation_completion_write git mv
_annotation_completion_write git reset
_annotation_completion_write git rm
_annotation_completion_write git bisect
_annotation_completion_write git grep
_annotation_completion_write git log
_annotation_completion_write git show
_annotation_completion_write git status
_annotation_completion_write git branch
_annotation_completion_write git checkout
_annotation_completion_write git commit
_annotation_completion_write git diff
_annotation_completion_write git merge
_annotation_completion_write git rebase
_annotation_completion_write git tag
_annotation_completion_write git fetch
_annotation_completion_write git pull
_annotation_completion_write git push

_completion_setup git
