#! /usr/bin/env bash

echo "$(curl -s https://golang.org/dl/ | pythongrep -o "(?<=<td\ class=\"filename\"><a\ class=\"download\"\ href=\").*?(?=\">)" | pythongrep -v "src"| pythongrep -i "amd64.tar.gz" | pythongrep -i "linux" | head -1)"
