#! /usr/bin/env bash

echo "$(curl -s https://golang.org/dl/ | s -o "(?<=<td\ class=\"filename\"><a\ class=\"download\"\ href=\").*?(?=\">)" | s -v "src"| s -i "amd64.tar.gz" | s -i "linux" | head -1)"
