#! /usr/bin/env bash

echo "$(curl -s https://golang.org/dl/ | pythongrep -o "(?<=<td\ class=\"filename\"><a\ class=\"download\"\ href=\").*?(?=\">)" | pythongrep -v "src"| pythongrep -i "tar.gz" | pythongrep -i "darwin" | head -1)"
