#! /usr/bin/env bash

# echo "http://ghaffarian.net/downloads/Java/$(curl -s http://ghaffarian.net/downloads/Java/ | s -o "(?<=<a\ href=\").*?(?=\">)" | s x64.tar.gz | sort | uniq | s 8u | head -1)"

# https://lv.binarybabel.org/api

curl -s https://lv.binarybabel.org/catalog-api/java/jdk8.txt?p=downloads.tgz
