#! /usr/bin/env bash

# echo "http://ghaffarian.net/downloads/Java/$(curl -s http://ghaffarian.net/downloads/Java/ | s -o "(?<=<a\ href=\").*?(?=\">)" | s x64.tar.gz | sort | uniq | s 7u | head -1)"

curl -s https://lv.binarybabel.org/catalog-api/java/jdk7.txt?p=downloads.tgz
