#! /usr/bin/env bash

latest_version_code=$(curl -s https://jsoup.org/news/ | s "/news/release" | s -o "(?<=href=\").*?(?=\">)" | head -1 | s -o "(?<=/news/release-).*")

echo "https://jsoup.org/packages/jsoup-$(_latest_jsoup_version_code).jar"

unset latest_version_code