#! /usr/bin/env bash

latest_version_code=$(curl -s https://jsoup.org/news/ | pythongrep "/news/release" | pythongrep -o "(?<=href=\").*?(?=\">)" | head -1 | pythongrep -o "(?<=/news/release-).*")

echo "https://jsoup.org/packages/jsoup-$latest_version_code.jar"

unset latest_version_code
