#! /usr/bin/env bash

url="http://ghaffarian.net/downloads/Java/$(curl -s http://ghaffarian.net/downloads/Java/ | s -o "(?<=<a\ href=\").*?(?=\">)" | s x64.tar.gz | sort | uniq | s 8u | head -1)"
echo $url
unset url
