#! /usr/bin/env bash

latest_version_code=$(curl -s https://www.xquartz.org/ | pythongrep 'https://dl.bintray.com/xquartz/downloads' | pythongrep -o '(?<=href=\").*?(?=\"\>\<span)')
echo "$latest_version_code"
unset latest_version_code
