#! /usr/bin/env bash

# http://developer.android.com/intl/ja/tools/publishing/app-signing.html
if [[ "$#" -lt 3 ]];then
    echo "Usage: command keystore apk alias_name"
else
    keystore="$1"
    apk="$2"
    alias_name="$3"
    cp -v "$apk" "signed_$apk" && [[ -f "signed_$apk" ]] && jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore "$keystore" "signed_$apk" "$alias_name"
    echo "Ouput: signed_$apk"
fi
