#! /usr/bin/env bash

# https://developer.android.com/studio/publish/app-signing
if [[ "$#" == 2 ]];then
    # https://stackoverflow.com/questions/67631927/error-building-aab-flutter-android-integrity-check-failed-java-security-n
    # in order to fix this, just specify the storetype argument
    /Applications/Android\ Studio.app/Contents/jre/Contents/Home/bin/keytool -genkey -v -keystore "$1" -alias "$2" -keyalg RSA -keysize 2048 -validity 10000 -storetype JKS
else
    echo "Usage: command key.keystore alias_name"
fi
