#! /usr/bin/env bash

VERSION_CODE=$(curl -s https://bitbucket.org/iBotPeaches/apktool/downloads/ | s 'iBotPeaches/apktool/downloads' | s -o '(?<=apktool_).*?(?=.jar)' | head -1)
# https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.2.1.jar
url="https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_$VERSION_CODE.jar"
echo $url

if [[ ! -f "$MY_BIN/apktool" ]];then
    curl -C - https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/osx/apktool > "$MY_BIN/apktool" \
    && chmod 0755 "$MY_BIN/apktool"
fi

if [[ ! -f "$MY_BIN/apktool.jar" ]];then
    curl -L -C - "$url" > "$MY_BIN/apktool.jar"
fi
unset url
