#! /usr/bin/env bash

# http://developer.android.com/intl/ja/tools/publishing/app-signing.html
if [[ "$#" -lt 3 ]];then
    echo "Usage: command keystore apk alias_name"
else
    keystore="$1"
    apk="$2"
    alias_name="$3"
    cp -v "$apk" "$apk.signed"
    jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $keystore $apk.signed $alias_name || rm -v "$apk.signed"
fi
