#! /usr/bin/env bash

latest_version_code=$(curl -s https://gradle.org/releases/ | s -o '(?<=https://services.gradle.org/distributions/gradle-).*?(?=-bin.zip)' | head -1)
echo "https://services.gradle.org/distributions/gradle-$latest_version_code-all.zip"
unset latest_version_code
