#! /usr/bin/env bash

(
if [[ ! "$#" -eq 1 ]];then
    echo "Usage: repos_register_all <path>"
    exit
else
    mrconfig_directory=$1
    repos_directory=$1
fi

if [[ -f "$mrconfig_directory/.mrconfig" ]];then
    rm -v "$mrconfig_directory/.mrconfig"
fi

while IFS= read -r file
do
    if [[ -d "$file/.git" ]];then
        url=$(repos_git_get_url "$file")
        echo $file -- $url
        echo "[${file/#$HOME\//}]" >> "$mrconfig_directory/.mrconfig" \
            && echo "checkout = git clone '"$url"' '"${file/#$HOME\//}"'" >> "$mrconfig_directory/.mrconfig"
    fi
done < <(find "$repos_directory" -mindepth 1 -maxdepth 1 -type d)
)
