#!/usr/bin/env python

import sys, uuid

s = ''
if len(sys.argv) != 2 or sys.argv[1] == '-':
    s = sys.stdin.read().strip()
else:
    s = sys.argv[1]

print uuid.UUID(hex(int(s, 36))[2:-1].zfill(32))
