#! /usr/bin/env python

import glob, os, sys

# checking whether path and filename are given.
if len(sys.argv) != 4:
    print("Usage : rename 'pattern' 'old_str' 'new_str'")
    print("All arguments must be surrounded with single quote to avoid being expanded")
    sys.exit()

# pattern to match file for process
def rename(pattern, old_str, new_str):
    dirName = os.path.realpath(os.curdir)
    for f in glob.iglob(os.path.join(dirName, pattern)):
        fileName = os.path.basename(f).replace(old_str, new_str)
        os.rename(f, os.path.join(dirName, fileName))

rename(sys.argv[1], sys.argv[2], sys.argv[3])
