#! /usr/bin/env bash

if [[ "$(readlink ~/.vimrc)" =~ .*\.vimrc\.heavy ]];then
    echo "currently using .vimrc.heavy"
    rm -vf ~/.vimrc
    echo "switching to .vimrc.light"
    ln -s ~/.dotfiles/.vimrc.light ~/.vimrc
else
    echo "currently using .vimrc.light"
    rm -vf ~/.vimrc
    echo "switching to .vimrc.heavy"
    ln -s ~/.dotfiles/.vimrc.heavy ~/.vimrc
fi
