_myload_sh_files $MY_SH_MODULE android
_myload_sh_files $MY_SH_MODULE c
_myload_sh_files $MY_SH_MODULE cabal
_myload_sh_files $MY_SH_MODULE enchancd
_myload_sh_files $MY_SH_MODULE flatbuffers
_myload_sh_files $MY_SH_MODULE fpp
_myload_sh_files $MY_SH_MODULE go
_myload_sh_files $MY_SH_MODULE history
_myload_sh_files $MY_SH_MODULE java
_myload_sh_files $MY_SH_MODULE macports-tools
_myload_sh_files $MY_SH_MODULE myfzf
_myload_sh_files $MY_SH_MODULE myrepos
_myload_sh_files $MY_SH_MODULE mytranslate
_myload_sh_files $MY_SH_MODULE myvi
_myload_sh_files $MY_SH_MODULE nvm
_myload_sh_files $MY_SH_MODULE prompt
_myload_sh_files $MY_SH_MODULE python
_myload_sh_files $MY_SH_MODULE rvm
_myload_sh_files $MY_SH_MODULE scala
_myload_sh_files $MY_SH_MODULE sdkman
_myload_sh_files $MY_SH_MODULE vundle
_myload_sh_files $MY_SH_MODULE xkcdpass
_myload_sh_files $MY_SH_MODULE z
