#! /usr/bin/env bash

_percol() {
    percol --match-method regex "$@"
}

FILTER="$(svn_filter)"

#svn changelist stash $(svn status | _percol | gawk '{print $2}')
# svn changelist do not support directory
svn status | pythongrep -v "$FILTER" | grep '?' |gawk '{print $2}' > /tmp/_svn_changelist_stash
