#! /usr/bin/env bash

FILTER="$(svn_filter)"

FILE=$(svn status | pythongrep "^M" | pythongrep -v "$FILTER" | percol --match-method regex | gawk '{print $2}')


if command -v icdiff > /dev/null;then
    if [[ "${#FILE}" -gt 0 ]];then
        svn diff --diff-cmd icdiff $FILE
    fi
else
    if [[ "${#FILE}" -gt 0 ]];then
        svn diff $FILE
    fi
fi
