#! /usr/bin/env bash

FILTER="$(svn_filter)"

FILE=$(svn status | pythongrep -v "$FILTER" | grep '?' | percol --match-method regex | gawk '{print $2}')

if [[ "${#FILE}" -gt 0 ]];then
    svn add $FILE
fi
