#! /usr/bin/env bash

SELECTION="$(svn log -q "$1" | grep "^r[0-9]" | percol --match-method regex | gawk '{print $1}') "$1""

if [[ ${#SELECTION} -gt 0 ]];then
    if command -v icdiff > /dev/null;then
        svn diff --diff-cmd icdiff -r $SELECTION
    else
        svn diff -r $SELECTION
    fi
fi