#! /usr/bin/env bash

_percol() {
    percol --match-method regex "$@"
}

FILE=$(svn status | pythongrep -v '(/obj|/bin)' | _percol | gawk '{print $2}')

if [[ "${#FILE}" -gt 0 ]];then
    svn diff --diff-cmd icdiff $FILE
fi
