#! /usr/bin/env bash

FILTER="$(svn_filter)"

#svn changelist stash $(svn status | percol --match-method | gawk '{print $2}')
# svn changelist do not support directory
svn status | pythongrep -v "$FILTER" | gawk '{print $2}' > /tmp/_svn_changelist_stash
