#! /usr/bin/env bash

_is_command_exist() {
    [[ "$#" -eq 1 ]] && command -v "$1" > /dev/null
}

if _is_command_exist 'nvim';then
    nvim /tmp/_svn_changelist_stash
elif _is_command_exist 'vim';then
    vim /tmp/_svn_changelist_stash
fi
