#! /usr/bin/env bash

SELECTION="$(git status -s | gawk '{print $2}' | percol --match-method regex)"

if [[ ${#SELECTION} -gt 0 ]];then
    if command -v 'git-icdiff' > /dev/null; then
        git-icdiff $SELECTION
    else
        git diff $SELECTION
    fi
fi
