#! /usr/bin/env bash

if [[ -f './cscope.files' ]];then
    echo "cscope indexing ..."
    cscope -bckq -i './cscope.files'

    echo "ctags indexing ..."
    ctags -L ./cscope.files --tag-relative=yes './tags'

    echo "gnu global indexing ..."
    # gtags on ubuntu does not support '--skip-unreadable'
    gtags -f ./cscope.files
else
    echo "Plz generate file list first!"
fi
