#! /usr/bin/env bash

echo "generating file list for current directory ..."
find "$(pwd)" -name '*.aidl' -o -name '*.cc' -o -name '*.h' -o -name '*.c' -o -name '*.cpp' -o -name '*.java' | s -i -v 'test' | _readlink | sort | uniq > './cscope.files'
echo "output: cscope.files"

