#! /usr/bin/env python3
# coding=UTF-8

from __future__ import print_function
import os
import sys

DIRS = []
if os.path.isdir(os.getcwd()):
    for f in os.listdir(os.getcwd()):
        if os.path.isdir(os.path.abspath(f)):
            DIRS.append(os.path.abspath(f))

SORTED_DIRS = sorted(DIRS)

if len(sys.argv) > 1:
    try:
        print(SORTED_DIRS[int(sys.argv[1])])
    except ValueError:
        sys.exit(0)
else:
    for i in range(len(SORTED_DIRS)):
        print('[' + str(i) + ']' + SORTED_DIRS[i])
