#! /usr/bin/env python3
# coding=UTF-8

from __future__ import print_function
import os
import sys

current_dir = os.getcwd()

DIRS = []

candidate = current_dir.split('/')

for i in range(0, len(candidate)):
    path = ''
    for j in range(0, i+1):
        path += candidate[j] + '/'
    DIRS.append(path)

if len(sys.argv) > 1:
    try:
        print(DIRS[int(sys.argv[1])])
    except ValueError:
        sys.exit(0)
else:
    for i in range(0, len(DIRS)):
        print('[' + str(i) + ']' + DIRS[i])



